[book]
title = "mdutils Example"
authors = ["mdutils contributors"]

[build]
build-dir = "book"

[preprocessor.util-banner]
command = "mdutils"
position = "top"
sticky = false

[preprocessor.util-private-page]
command = "mdutils"
hide_sidebar = true
hide_nav_buttons = true
