[package]
name = "mdutils"
version = "0.1.5"
edition = "2021"
description = "Utility preprocessors for mdBook"
license = "MIT"

[[bin]]
name = "mdutils"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
mdbook-preprocessor = "0.5"
pathdiff = "0.2"
pulldown-cmark = { version = "0.13", default-features = false, features = ["html"] }
regex = "1"
serde_json = "1"
